### ISSUE TITLE
Switch router to auto scaling

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#1313]
...within bounds.

**Comment by snarfed** [comment]
Trying this out with this config, looking ok so far.

```yaml
automatic_scaling:
  min_num_instances: 2
  max_num_instances: 6
  cpu_utilization:
    target_utilization: 0.9
```
