### ISSUE TITLE
Netlify Redirects

### ISSUE THREAD

**Issue by miklb** [snarfed/bridgy-fed#337]
howdy! So glad to see your recent posts in the feed reader.

I'm trying to start fresh with a new indie domain and am using Eleventy on Netlify for the time being.

My current rewrites are

```
[[redirects]]
  from = "/.well-known/host-meta*"
  to = "https://fed.brid.gy/.well-known/host-meta.*"

[[redirects]]
  from = "/.well-known/webfinger*"
  to = "https://fed.brid.gy/.well-known/webfinger.*"
```

I'm putting the cart a bit before the horse in getting this configured before fully implementing mf2 and starting to post again, but I'm also using it as motivation.

It *appears* webfinger is working, but I still get the `Next step: add the .well-known redirects` message. 

Any thoughts on what's amiss?

domain is michaelbishop.me

**Comment by miklb** [comment]
Just realized I was using `meta*` and not `meta.*` in the from redirect. Changing that now to see if that was the issue.

**Comment by snarfed** [comment]
Hey, welcome back! Thanks for trying Bridgy Fed!

Right now, it looks like eg https://michaelbishop.me/.well-known/webfinger?x=y redirects to https://www.michaelbishop.me/.well-known/webfinger?x=y (note the www), which then 404s.

**Comment by miklb** [comment]
OK, so now it's reporting
```
https://michaelbishop.me/.well-known/webfinger?resource=acct:michaelbishop.me@michaelbishop.me
  redirected to:
https://fed.brid.gy/.well-known/webfinger*?resource=acct:michaelbishop.me@michaelbishop.me
  returned HTTP 404
```

**Comment by miklb** [comment]
is it because I have the `acct:michael@michaelbishop.me` in the `h-card`?

**Comment by snarfed** [comment]
HTTP redirects are unrelated to what's in your h-card.

**Comment by snarfed** [comment]
Looks like that error message is right, your site is now redirecting to `https://fed.brid.gy/.well-known/webfinger*?...` with a literal `*` character at the end of the path. You'll want to remove that 😁

**Comment by aciccarello** [comment]
Here are the netlify redirects I am using for my site

```toml
[[redirects]]
  from = "/.well-known/host-meta*"
  to = "https://fed.brid.gy/.well-known/host-meta:splat"
  status = 302
[[redirects]]
  from = "/.well-known/webfinger*"
  to = "https://fed.brid.gy/.well-known/webfinger"
  status = 302
```
https://github.com/aciccarello/ciccarello.me/blob/de10157f08f35f7bdf70eefdf48eaec16687ca9c/netlify.toml#L55-L62
